"""Canonical platform architecture registry — maps all 16 sectors to EAM layers."""

from __future__ import annotations

from typing import Any, Literal

LayerStatus = Literal["LIVE", "PARTIAL", "PLANNED", "CMS_ONLY", "BLOCKED"]

# Shared platform business services (cross-cutting)
PLATFORM_BUSINESS_SERVICES: list[dict[str, str]] = [
    {"id": "jos", "label_ar": "JOS — تنسيق الرحلات", "authority": "services/jos.py"},
    {"id": "service_request", "label_ar": "طلب الخدمة (SR)", "authority": "services/service_requests.py"},
    {"id": "professional_review", "label_ar": "المراجعة المهنية", "authority": "operations_service_requests"},
    {"id": "quote", "label_ar": "عرض السعر", "authority": "services/quotes.py"},
    {"id": "customer_workspace", "label_ar": "مساحة العميل", "authority": "services/customer_360.py"},
    {"id": "ai_core", "label_ar": "AI Core", "authority": "services/ai_core.py"},
    {"id": "tool_gateway", "label_ar": "Tool Gateway", "authority": "routers/ai_tools.py"},
    {"id": "partner_platform", "label_ar": "منصة الشركاء B2B", "authority": "services/partners.py"},
    {"id": "procurement_order", "label_ar": "أمر الشراء / التوريد", "authority": "services/procurement_orders.py"},
    {"id": "logistics", "label_ar": "الطبقة اللوجستية (التوصيل)", "authority": "services/logistics.py"},
    {"id": "payment", "label_ar": "المدفوعات (Stripe)", "authority": "services/payment.py"},
    {"id": "command_center", "label_ar": "لوحة القيادة", "authority": "services/operations_dashboard.py"},
    {"id": "cms", "label_ar": "المحتوى التحريري", "authority": "CMS routers"},
]

PLATFORM_SECTOR_ARCHITECTURE: list[dict[str, Any]] = [
    {
        "sector_number": 1,
        "sector_slug": "real-estate-development",
        "title_ar": "التطوير العقاري",
        "business_capability": "real_estate_development",
        "journey_type": "real_estate_development",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {
            "marketing_route": "/services/real-estate-development",
            "journey_route": "/journeys/real-estate-development",
        },
    },
    {
        "sector_number": 2,
        "sector_slug": "real-estate-marketing",
        "title_ar": "التسويق العقاري",
        "business_capability": "real_estate_marketing",
        "journey_type": "real_estate_marketing",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {
            "marketing_route": "/services/real-estate-marketing",
            "journey_route": "/journeys/real-estate-marketing",
        },
    },
    {
        "sector_number": 3,
        "sector_slug": "investment",
        "title_ar": "الاستثمار",
        "business_capability": "investment",
        "journey_type": None,
        "journey_status": "BLOCKED",
        "business_services": ["cms", "command_center"],
        "business_objects": [],
        "experience": {"marketing_route": "/invest", "journey_route": None},
        "notes_ar": "رحلة الاستثمار BLOCKED_UPSTREAM — تجربة CMS فقط",
    },
    {
        "sector_number": 4,
        "sector_slug": "build-villa",
        "title_ar": "بناء منزل",
        "business_capability": "build_villa",
        "journey_type": "build_villa",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/journeys/build-villa", "journey_route": "/journeys/build-villa"},
    },
    {
        "sector_number": 5,
        "sector_slug": "real-estate-valuation",
        "title_ar": "التقييم العقاري",
        "business_capability": "real_estate_valuation",
        "journey_type": "real_estate_valuation",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {
            "marketing_route": "/sectors/real-estate-valuation",
            "journey_route": "/journeys/real-estate-valuation",
        },
    },
    {
        "sector_number": 6,
        "sector_slug": "government-services",
        "title_ar": "الخدمات الحكومية",
        "business_capability": "government_services",
        "journey_type": "government_services",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/government-services", "journey_route": "/journeys/government-services"},
    },
    {
        "sector_number": 7,
        "sector_slug": "project-management",
        "title_ar": "إدارة المشاريع",
        "business_capability": "project_management",
        "journey_type": "project_management",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {
            "marketing_route": "/sectors/project-management",
            "journey_route": "/journeys/project-management",
        },
    },
    {
        "sector_number": 8,
        "sector_slug": "engineering-consulting",
        "title_ar": "الاستشارات الهندسية",
        "business_capability": "engineering_consulting",
        "journey_type": "engineering_consulting",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/engineering-services", "journey_route": "/journeys/engineering-consulting"},
    },
    {
        "sector_number": 9,
        "sector_slug": "contracting",
        "title_ar": "المقاولات والتشييد",
        "business_capability": "contracting",
        "journey_type": "contracting",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/services/contracting", "journey_route": "/journeys/contracting"},
    },
    {
        "sector_number": 10,
        "sector_slug": "building-materials",
        "title_ar": "مواد البناء",
        "business_capability": "building_materials_procurement",
        "journey_type": "building_materials",
        "journey_status": "LIVE",
        "business_services": [
            "jos",
            "service_request",
            "procurement_order",
            "logistics",
            "partner_platform",
            "quote",
            "payment",
            "professional_review",
            "customer_workspace",
            "ai_core",
        ],
        "business_objects": [
            "ServiceRequest",
            "ProcurementOrder",
            "DeliveryShipment",
            "Quote",
            "JourneyInstance",
            "PartnerOrganization",
        ],
        "experience": {
            "marketing_route": "/sectors/building-materials",
            "journey_route": "/journeys/building-materials",
        },
        "notes_ar": "أمر الشراء (PO) يُنشأ تلقائياً من الفاتورة الأولية عند إرسال الطلب",
    },
    {
        "sector_number": 11,
        "sector_slug": "equipment",
        "title_ar": "المعدات والآلات",
        "business_capability": "equipment",
        "journey_type": "equipment",
        "journey_status": "LIVE",
        "business_services": [
            "jos",
            "service_request",
            "procurement_order",
            "logistics",
            "partner_platform",
            "quote",
            "professional_review",
            "customer_workspace",
            "ai_core",
        ],
        "business_objects": ["ServiceRequest", "ProcurementOrder", "DeliveryShipment", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/sectors/equipment", "journey_route": "/journeys/equipment"},
        "notes_ar": "PO أولي من موجز المعدات عند الإرسال — نفس سلسلة الشريك/الشحن عند الإسناد",
    },
    {
        "sector_number": 12,
        "sector_slug": "factories-suppliers",
        "title_ar": "المصانع والموردين",
        "business_capability": "factories_suppliers",
        "journey_type": None,
        "journey_status": "PLANNED",
        "business_services": ["cms", "partner_platform", "command_center"],
        "business_objects": ["PartnerOrganization", "PartnerOutlet"],
        "experience": {"marketing_route": "/sectors/factories-suppliers", "journey_route": None},
        "notes_ar": "ربط B2B عبر الشركاء — رحلة JOS لاحقاً",
    },
    {
        "sector_number": 13,
        "sector_slug": "smart-maintenance",
        "title_ar": "التشغيل والصيانة الذكية",
        "business_capability": "smart_maintenance",
        "journey_type": "smart_maintenance",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/services/maintenance", "journey_route": "/journeys/smart-maintenance"},
    },
    {
        "sector_number": 14,
        "sector_slug": "facility-management",
        "title_ar": "إدارة المرافق",
        "business_capability": "facility_management",
        "journey_type": "facility_management",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {
            "marketing_route": "/sectors/facility-management",
            "journey_route": "/journeys/facility-management",
        },
    },
    {
        "sector_number": 15,
        "sector_slug": "furnishing",
        "title_ar": "التأثيث والتجهيز",
        "business_capability": "furnishing",
        "journey_type": "furnishing",
        "journey_status": "LIVE",
        "business_services": ["jos", "service_request", "quote", "professional_review", "customer_workspace", "ai_core"],
        "business_objects": ["ServiceRequest", "Quote", "JourneyInstance"],
        "experience": {"marketing_route": "/sectors/furnishing", "journey_route": "/journeys/furnishing"},
    },
    {
        "sector_number": 16,
        "sector_slug": "delivery-warranty",
        "title_ar": "التسليم وخدمات الملاك",
        "business_capability": "delivery_warranty",
        "journey_type": None,
        "journey_status": "PLANNED",
        "business_services": ["cms", "command_center"],
        "business_objects": [],
        "experience": {"marketing_route": "/sectors/delivery-warranty", "journey_route": None},
        "notes_ar": "يتطلب OperationalProject — BLOCKED_UPSTREAM",
    },
]


def get_platform_architecture() -> dict[str, Any]:
    live_journeys = sum(1 for s in PLATFORM_SECTOR_ARCHITECTURE if s.get("journey_status") == "LIVE")
    return {
        "schema_version": "2026-09-21",
        "layer_model": [
            "business_capability",
            "journey",
            "workflow",
            "business_services",
            "business_objects",
            "experience",
        ],
        "workflow_authority": "JOS (journey_definitions + journey_instances)",
        "platform_business_services": PLATFORM_BUSINESS_SERVICES,
        "sectors": PLATFORM_SECTOR_ARCHITECTURE,
        "summary": {
            "sector_count": len(PLATFORM_SECTOR_ARCHITECTURE),
            "live_journey_count": live_journeys,
            "planned_or_blocked_sectors": len(PLATFORM_SECTOR_ARCHITECTURE) - live_journeys,
        },
    }
